spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zrnzdprqqjvsmliswugt
spring.datasource.password=YOUR_PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

# 🔥 CRITICAL FOR POOLER
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0

# 🔥 DISABLE HIBERNATE FEATURES THAT BREAK
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

server.port=${PORT:8080}